language: cpp
os:
  - linux
  - osx
compiler: 
  - gcc
  - clang
cache:
  apt: true
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - clang-3.7
      - g++-5.0
      - gcc-5.0
      - libboost1.55-all-dev
notifications:
  email: false
script: 
  - cmake .; make; bin/mcmc_history -e dataset/southernWomen.edgelist0 -n 4 4 4 3 3 3 3 3 3 2 -t 1000 -y 18 14 -z 5 5 --estimate -f 10
